# Generated by Django 6.1 on 2026-08-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_translit_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Дата старта')),
                ('days_total', models.PositiveIntegerField(default=30, verbose_name='Всего дней')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Челлендж',
                'verbose_name_plural': 'Челленджи',
            },
        ),
        migrations.CreateModel(
            name='JobSearchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applications', models.PositiveIntegerField(default=0, verbose_name='Откликов отправлено')),
                ('interviews', models.PositiveIntegerField(default=0, verbose_name='Собеседований')),
                ('offers', models.PositiveIntegerField(default=0, verbose_name='Офферов')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статистика поиска работы',
                'verbose_name_plural': 'Статистика поиска работы',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='project_slug',
            field=models.CharField(blank=True, help_text='Слаг проекта из /admin/portfolio/project/ — ссылка на его карточку на главной', max_length=100, verbose_name='Проект (слаг на главной)'),
        ),
    ]
