# Generated by hand: Challenge-рефакторинг — поля по схеме «отдельная модель + FK из постов».
# name->title, days_total->total_days, active->is_active, добавлены slug/description,
# у Post добавлены challenge (FK) и day_number.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_challenge_jobsearchstats_post_project_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='days_total',
            new_name='total_days',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='post',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.challenge', verbose_name='Челлендж'),
        ),
        migrations.AddField(
            model_name='post',
            name='day_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='День N'),
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-start_date'], 'verbose_name': 'Челлендж', 'verbose_name_plural': 'Челленджи'},
        ),
    ]
