# Generated by Django 6.1 on 2026-08-30 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_backfill_path_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('fire', '🔥'), ('rocket', '🚀'), ('dislike', '👎')], max_length=20, verbose_name='Реакция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blog.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
                'ordering': ['created_at'],
            },
        ),
    ]
