# Generated by Django 6.1 on 2026-08-30 23:59

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_postreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Картинка для превью при шаринге. Приоритетнее первой картинки из текста.', null=True, upload_to='posts/', verbose_name='Обложка (для превью)'),
        ),
    ]
