# Generated by Django 6.1 on 2026-08-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
