# Generated by Django 6.1 on 2026-08-31 09:03

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_set_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='applications_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Откликов отправлено'),
        ),
        migrations.AddField(
            model_name='post',
            name='interviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Собеседований'),
        ),
        migrations.AddField(
            model_name='post',
            name='offers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Офферов'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Картинки, вставленные через редактор, не отслеживаются автоматически. Проверяйте вручную перед удалением файлов из медиа.', verbose_name='Текст поста'),
        ),
    ]
