# Generated by Django 6.1 on 2026-08-29 18:48

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tech_stack', models.CharField(help_text='Через запятую: FastAPI, Postgres, Docker', max_length=200)),
                ('github_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('wip', 'In progress')], default='live', max_length=10)),
                ('cover_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
