# Generated by Django 6.1 on 2026-08-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
