# Generated by Django 6.1 on 2026-09-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='period_text',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, help_text='Не заполняйте, если работаете по настоящее время', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(choices=[('open_to_work', 'Рассматриваю предложения'), ('actively_looking', 'В активном поиске'), ('not_looking', 'Не ищу работу')], default='open_to_work', max_length=20),
        ),
    ]
